#!/usr/bin/env sh
set -eu

CONSTITUTION_RUNTIME_DIR="${CONSTITUTION_RUNTIME_DIR:-.local/constitution}"
CONSTITUTION_EVIDENCE_DIR="${CONSTITUTION_EVIDENCE_DIR:-$CONSTITUTION_RUNTIME_DIR/evidence}"
CONSTITUTION_CACHE_DIR="${CONSTITUTION_CACHE_DIR:-$CONSTITUTION_RUNTIME_DIR/cache}"
CONSTITUTION_LOG_DIR="${CONSTITUTION_LOG_DIR:-$CONSTITUTION_RUNTIME_DIR/logs}"

export CONSTITUTION_RUNTIME_DIR
export CONSTITUTION_EVIDENCE_DIR
export CONSTITUTION_CACHE_DIR
export CONSTITUTION_LOG_DIR
